Homework3/Models/FileModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Homework3.Models
{
    public class FileModel
    {
        //Display options.

        [Display(Name = "File Name")]
        public string FileName { get; set; }

        [Required(ErrorMessage = "Please select file.")]
        [Display(Name = "Browse File")]
        public HttpPostedFileBase[] Files { get; set; }
    }
}

Homework3/Controllers/FileDownloadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Homework3.Models;
using System.IO;
using System.Collections.Generic;

namespace Homework3.Controllers
{
    public class FileDownloadController : Controller
    {
        // GET: FileDownload
        public ActionResult Index()
        {
            string[] filePaths = Directory.GetFiles(Server.MapPath("~/App_Data/uploads/"));

            List<FileModel> files = new List<FileModel>();

            foreach (string filePath in filePaths)
            {
                files.Add(new FileModel { FileName = Path.GetFileName(filePath) });
            }
            return View(files);
        }

        public FileResult DownloadFile(string fileName)
        {
            //Build the File Path.

            string path = Server.MapPath("~/App_Data/uploads/") + fileName;

            //Read the File data into Byte Array.
            //Use a byte array becasue of octet-stream.

            byte[] bytes = System.IO.File.ReadAllBytes(path);

            return File(bytes, "application/octet-stream", fileName);
        }
        public ActionResult DeleteFile(string fileName)
        {
            //Delete requires reading the files and then the allocation of a file path.
            //The file is then deleted based on the identified file path.

            string path = Server.MapPath("~/App_Data/uploads/") + fileName;
            byte[] bytes = System.IO.File.ReadAllBytes(path);

            System.IO.File.Delete(path);
            return RedirectToAction("Index");
        }

        }
}

Homework3/Controllers/FileUploadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;

namespace Homework3.Controllers
{
    public class FileUploadController : Controller
    {
        // GET: FileUpload
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        //Single File Upload
        [HttpPost]
        public ActionResult Index(HttpPostedFileBase files)
        {
            if (files != null && files.ContentLength > 0)
            {
                // extract only the filename

                var fileName = Path.GetFileName(files.FileName);

                // store the file inside ~/App_Data/uploads folder
                var path = Path.Combine(Server.MapPath("~/App_Data/uploads"), fileName);

                // The chosen default path for saving

                files.SaveAs(path);
            }

            return RedirectToAction("Index"); 
        }
    }
}

Homework3/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Homework3.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Homework3/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using Homework3.Models;
using System.Collections.Generic;



namespace Homework3.Controllers
{
    public class ImageController : Controller
    {
        // GET: Image
        public ActionResult Index()
        {
            string[] filePaths = Directory.GetFiles(Server.MapPath("~/App_Data/Images/"));

            List<FileModel> files = new List<FileModel>();

            foreach (string filePath in filePaths)
            {
                files.Add(new FileModel { FileName = Path.GetFileName(filePath) });
            }
            return View(files);
            }

        public ActionResult Downloadimage(string Imagename)
        {
            //Build the File Path.

            string path = Server.MapPath("~/App_Data/Images/") + Imagename;

            //Read the File data into Byte Array.
            //Use a byte array becasue of octet-stream.

            byte[] bytes = System.IO.File.ReadAllBytes(path);

            return File(bytes, "application/octet-stream", Imagename);
        }

        public ActionResult DeleteImage(string Imagename)
        {
            //Delete requires reading the files and then the allocation of a file path.
            //The file is then deleted based on the identified file path.

            string path = Server.MapPath("~/App_Data/Images/") + Imagename;
            byte[] bytes = System.IO.File.ReadAllBytes(path);

            System.IO.File.Delete(path);
            return RedirectToAction("Index");
        }

    }
    }

Homework3/Controllers/VideoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Collections.Generic;
using Homework3.Models;

namespace Homework3.Controllers
{
    public class VideoController : Controller
    {
        // GET: Video
        public ActionResult Index()
        {
            string[] filePaths = Directory.GetFiles(Server.MapPath("~/App_Data/Videos/"));

            List<FileModel> files = new List<FileModel>();

            foreach (string filePath in filePaths)
            {
                files.Add(new FileModel { FileName = Path.GetFileName(filePath) });
            }
            return View(files);
        }
        public ActionResult DownloadVideo(string VideoName)
        {
            //Build the File Path.

            string path = Server.MapPath("~/App_Data/Videos/") + VideoName;

            //Read the File data into Byte Array.
            //Use a byte array becasue of octet-stream.

            byte[] bytes = System.IO.File.ReadAllBytes(path);
            return File(bytes, "application/octet-stream", VideoName);
        }

        public ActionResult DeleteVideo(string VideoName)
        {
            //Delete requires reading the files and then the allocation of a file path.
            //The file is then deleted based on the identified file path.

            string path = Server.MapPath("~/App_Data/Images/") + VideoName;
            byte[] bytes = System.IO.File.ReadAllBytes(path);

            System.IO.File.Delete(path);
            return RedirectToAction("Index");
        }
    } 
}

Homework3/Views/FileDownload/index.cshtml
@model IEnumerable<Homework3.Models.FileModel>
@using Homework3.Models

@{
    ViewBag.Title = "index";
}

<h2>index</h2>

<head>
    <style type="text/css">
        .auto-style {
            color: #FFFFFF;
        }

        .t {
            text-align: center;
            vertical-align: middle;
        }
    </style>
</head>
<div class="well-sm">
    <h2>File Download / Delete</h2>
    <p>
        I have set the  Downloading of files from the "App_Data/uploads/" folder
    </p>
</div>

@*
    Will generate as item but can be renamed.
*@
<div style="height: 400px; overflow: auto;">
    <div class="well-sm">
        <table class="table table-condensed table-hover">
            <thead style="position: sticky;top: 0">
                <tr bgcolor="#222222" class="auto-style">
                    <th class="col-lg-8">File Name</th>
                    <th class="t, col-lg-2">DOWNLOAD</th>
                    <th class="t, col-lg-2">DELETE</th>
                </tr>
            </thead>
            @foreach (FileModel file in Model)
            {
                <tr>
                    @*
                        Default >> @Html.DisplayFor(modelItem => file.FileName)
                    *@

                    <td>@file.FileName</td>
                    <td>
                        <button>
                            @Html.ActionLink("Download", "DownloadFile",
                             new { fileName = file.FileName })
                        </button>
                    </td>
                    <td>
                        <button>
                            @Html.ActionLink("DELETE", "DeleteFile",
                           new { fileName = file.FileName },
                           new { onclick = "return confirm('Are you sure you wish to delete this?');" })
                        </button>
                    </td>
                </tr>
            }
        </table>
    </div>
</div>

Homework3/Views/FileUpload/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div class="well-sm">
    <h2>Uploading</h2>
    <p></p>
<div class="well-sm">
    <div class="form-horizontal">
        @using (Html.BeginForm("Index", "FileUpload", FormMethod.Post, new { enctype = "multipart/form-data" }))

        // an encoding type that allows files to be sent through a POST.
        // Quite simply, without this encoding the files cannot be sent through POST.
        {
            <div><input type="file" name="files" /></div>
            <br />
            <div><input type="submit" value="Upload" /></div>
        }
    </div>
    <br />
</div>

Homework3/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="well-sm">
    <h2>About Me</h2>
</div>

<div class="well-sm">
    <p>My Name is Thendo Mudau. I am a Bcom Informatics Student at the University of Pretoria.I have a Passion for Cars but my biggest would be aviation and Aeroplanes. I have dreams and Aspirations of One day becoming an Airline Pilot.</p>

    <p>I am often asked why did i come to Varsity if i have intentions of studying and my answer is i always wanted something as a back up incase my flying did not work out. I also believe having a tertiary education also sets us apart from others.</p>

    <br />

    <p>I am the oldest with a Younger sister who is currently in her matric year this year. I am keep to see what programing has in store for me for the remainder of the year. I trust you have enjoyed listening to a short description about me.</p>
</div>

</div>

Homework3/Views/Image/Images.cshtml
@{
    ViewBag.Title = "Images";
}

<h2>Images</h2>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>


<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css" type="text/css" media="screen" />
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js"></script>

<div class="gallery">
    <a href="fullsize.png"><img src="thumbnail.png"></a>
    <a href="fullsize.png"><img src="thumbnail.png"></a>
    <a href="fullsize.png"><img src="thumbnail.png"></a>
    ...
</div>

<script>
    $(document).ready(function () {
        $(".gallery a").fancybox();
    });
</script>

Homework3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("File Uploading", "Index", "FileUpload")</li>
                    <li>@Html.ActionLink("File Downloading", "Index", "FileDownload")</li>



                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>